config/routes.rb
FIFA::Application.routes.draw do

	# staticstics
  match '/statistics/league_player_points', :controller => 'statistics', :action => 'league_player_points'
  match '/statistics/league_double_team_standings', :controller => 'statistics', :action => 'league_double_team_standings'
  match '/statistics/league_single_team_standings', :controller => 'statistics', :action => 'league_single_team_standings'

  resources :statistics

  resources :matches
  resources :teams
  
  # players
  match '/players/:id/ranking-over-time', :controller => 'players', :action => 'ranking_over_time'
  match '/players/:id/pie-chart', :controller => 'players', :action => 'pie_chart'
  match '/players/:id/matches', :controller => 'players', :action => 'matches'
  resources :players

  get "home/index"
  root :to => 'home#index'
end

app/models/statistic.rb
class Statistic
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  def index
    players = Player.all.to_a
    @standings = players.sort_by{|p| p.score}.reverse
    @teams = Team.all
  end

  # GET /statistics/1
  # GET /statistics/1.json
  def show
    @statistic = Statistic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @statistic }
    end
  end

  # GET /statistics/new
  # GET /statistics/new.json
  def new
    @statistic = Statistic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @statistic }
    end
  end

  # GET /statistics/1/edit
  def edit
    @statistic = Statistic.find(params[:id])
  end

  # POST /statistics
  # POST /statistics.json
  def create
    @statistic = Statistic.new(params[:statistic])

    respond_to do |format|
      if @statistic.save
        format.html { redirect_to @statistic, notice: 'Statistic was successfully created.' }
        format.json { render json: @statistic, status: :created, location: @statistic }
      else
        format.html { render action: "new" }
        format.json { render json: @statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  def league_player_points
  	players = Player.all.to_a
	  @standings = players.sort_by{|p| p.score}.reverse
  end


  def league_double_team_standings
  	@teams = Team.all.select{|t| t.players.length > 1}.sort_by{|t| t.points_per_game}.reverse
  end

  def league_single_team_standings
  	@teams = Team.all.select{|t| t.players.length == 1}.sort_by{|t| t.points_per_game}.reverse
  end

  # PUT /statistics/1
  # PUT /statistics/1.json
  def update
    @statistic = Statistic.find(params[:id])

    respond_to do |format|
      if @statistic.update_attributes(params[:statistic])
        format.html { redirect_to @statistic, notice: 'Statistic was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statistics/1
  # DELETE /statistics/1.json
  def destroy
    @statistic = Statistic.find(params[:id])
    @statistic.destroy

    respond_to do |format|
      format.html { redirect_to statistics_url }
      format.json { head :ok }
    end
  end
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/views/statistics/_form.html.erb
<%= form_for(@statistic) do |f| %>
  <% if @statistic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@statistic.errors.count, "error") %> prohibited this statistic from being saved:</h2>

      <ul>
      <% @statistic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statistics/_league_double_team.erb
<ul data-role="listview" class="ui-listview">
	<li data-role="list-divider" role="heading" class="ui-li ui-li-divider ui-btn ui-bar-d">
	Team standings
	</li>
</ul>
<br />

<table style="width:100%" id="result-table">
	<thead>
		<tr>
		<th style="text-align:left">Team</th>
		<th>P</th>
		<th>W</th>
		<th>L</th>
		<th>D</th>
		<th>PPG</th>
		</tr>
	</thead>
	<tbody>
		<% @teams.select{|t| t.players.length > 1}.each do |team| %>
		<tr>
		<td style="text-align:left"><%= team.display_name %></td>
		<td><%= team.matches.length %></td>
		<td class="green"><%= team.wins %></td>
		<td class="red"><%= team.losses %></td>
		<td><%= team.draws %></td>
		<td class="blue"><%= team.points_per_game.to_f %></td>
		</tr>
		<% end %>
	</tbody>
	<tfooter>
	</tfooter>
</table>

app/views/statistics/edit.html.erb
<h1>Editing statistic</h1>

<%= render 'form' %>

<%= link_to 'Show', @statistic %> |
<%= link_to 'Back', statistics_path %>

app/views/statistics/index.html.erb
<% content_for :body do %>

  <div data-role="header" data-theme="a">
		<a href="javascript:history.back()" data-icon="back" data-iconpos="notext" data-direction="reverse" class="ui-btn-left jqm-home">Back</a> 
		<h1>Statistics</h1>
    <a href="/" data-icon="home" data-iconpos="notext" data-direction="reverse" class="ui-btn-right jqm-home">Home</a>
  </div>

	<div data-role="content">


	<ul data-role="listview" data-inset="true">
		<li data-icon="star"><a href="/statistics/league_player_points">Player rankings</a></li>
	</ul>

	<ul data-role="listview" data-inset="true">
		<li data-icon="grid"><a href="/statistics/league_double_team_standings">Team league</a></li>
		<li data-icon="grid"><a href="/statistics/league_single_team_standings">Single league</a></li> 
	</ul>


</div>
<% end %>

app/views/statistics/league_double_team_standings.erb
<% content_for :body do %>

  <div data-role="header" data-theme="a">
 <a href="javascript:history.back()" data-icon="back" data-iconpos="notext" data-direction="reverse" class="ui-btn-left jqm-home">Back</a> 
	 <h1>Double league</h1>
    <a href="/" data-icon="home" data-iconpos="notext" data-direction="reverse" class="ui-btn-right jqm-home">Home</a>
  </div>


<div data-role="content">

<%= render :partial => "league_double_team", :locals => { :teams => @teams } %>

</div>
<% end %>

app/views/statistics/league_player_points.erb
<% content_for :body do %>

  <div data-role="header" data-theme="a">

 <a href="javascript:history.back()" data-icon="back" data-iconpos="notext" data-direction="reverse" class="ui-btn-left jqm-home">Back</a> 
    <h1>Player rankings</h1>
    <a href="/" data-icon="home" data-iconpos="notext" data-direction="reverse" class="ui-btn-right jqm-home">Home</a>
  </div>


<div data-role="content">

<ul data-role="listview" class="ui-listview">
	<li data-role="list-divider" role="heading" class="ui-li ui-li-divider ui-btn ui-bar-d">
	<div class="ui-grid-a">
			<div class="ui-block-a"  style="width:71%">
				Player
			</div>
			<div class="ui-block-b" style="width:20%;text-align:right;padding-right:10px;">
				Score
			</div>
		</div>	
	</li>
	<% @standings.each do |player| %>
	<li  data-theme="c" class="ui-btn ui-btn-icon-right ui-li-has-arrow ui-li ui-btn-up-c">
	<a href="<%= player_path(player) %>">
	<div class="ui-grid-a">
			<div class="ui-block-a"  style="width:75%;">
				<%= player.username %>	<br />	
				<%= render :partial => "/shared/rating", :locals => { :player => player } %>
			</div>
			<div class="ui-block-b" style="width:20%;text-align:right;padding:8px 10px 0 0 ;">
				<%= player.score %>
			</div>
		</div>	
	</a>
	</li>
	<% end %>
</ul>



</div>
<% end %>

app/views/statistics/league_single_team_standings.erb
<% content_for :body do %>

  <div data-role="header" data-theme="a">
 <a href="javascript:history.back()" data-icon="back" data-iconpos="notext" data-direction="reverse" class="ui-btn-left jqm-home">Back</a> 
	 <h1>Single league</h1>
    <a href="/" data-icon="home" data-iconpos="notext" data-direction="reverse" class="ui-btn-right jqm-home">Home</a>
  </div>


<div data-role="content">

<ul data-role="listview" class="ui-listview">
	<li data-role="list-divider" role="heading" class="ui-li ui-li-divider ui-btn ui-bar-d">
	Single team standings
	</li>
</ul>
<br />

<table style="width:100%" id="result-table">
	<thead>
		<tr>
		<th style="text-align:left">Team</th>
		<th>P</th>
		<th>W</th>
		<th>L</th>
		<th>D</th>
		<th>PPG</th>
		</tr>
	</thead>
	<tbody>
		<% @teams.each do |team| %>
		<tr>
		<td style="text-align:left"><%= team.display_name %></td>
		<td><%= team.matches.length %></td>
		<td class="green"><%= team.wins %></td>
		<td class="red"><%= team.losses %></td>
		<td><%= team.draws %></td>
		<td class="blue"><%= team.points_per_game %></td>
		</tr>
		<% end %>
	</tbody>
	<tfooter>
	</tfooter>
</table>


</div>
<% end %>

app/views/statistics/new.html.erb
<h1>New statistic</h1>

<%= render 'form' %>

<%= link_to 'Back', statistics_path %>

app/views/statistics/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_statistic_path(@statistic) %> |
<%= link_to 'Back', statistics_path %>