config/routes.rb
FIFA::Application.routes.draw do

	# staticstics
  match '/statistics/league_player_points', :controller => 'statistics', :action => 'league_player_points'
  match '/statistics/league_double_team_standings', :controller => 'statistics', :action => 'league_double_team_standings'
  match '/statistics/league_single_team_standings', :controller => 'statistics', :action => 'league_single_team_standings'

  resources :statistics

  resources :matches
  resources :teams
  
  # players
  match '/players/:id/ranking-over-time', :controller => 'players', :action => 'ranking_over_time'
  match '/players/:id/pie-chart', :controller => 'players', :action => 'pie_chart'
  match '/players/:id/matches', :controller => 'players', :action => 'matches'
  resources :players

  get "home/index"
  root :to => 'home#index'
end

app/models/player.rb
class Player < ActiveRecord::Base
  has_and_belongs_to_many :teams
  has_many :player_logs
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  # GET /players
  # GET /players.json
  
  helper_method :get_match_color
  
  def index
    @players = Player.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @players }
    end
  end
  
  def load_show_actions
  	@player = Player.find(params[:id])
    @player_matches = []
    
		 @player.teams.each do |team|
			team.matches.each do |match|
				@player_matches.push(match)
			end
		 end

   	@player_matches.sort_by!{|m| m.created_at}.reverse!
		get_player_statistics
  end

  # GET /players/1
  # GET /players/1.json
  def show
  	load_show_actions
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @player }
    end
  end
  
  def ranking_over_time
  	load_show_actions
  	
  	all_rankings = @player.player_logs.sort_by{|l| l.created_at}
		@historic_ranking_by_day = []
			
			previous_day = nil
			all_rankings.each_with_index do |r,index|
			
				if(!previous_day.nil? && r.created_at.day != previous_day.created_at.day)
					@historic_ranking_by_day.push(previous_day)
				end
				
				if(index == (all_rankings.length-1))
					@historic_ranking_by_day.push(r)
				end
			
				previous_day = r
			end
  	
   	 respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @player }
    end
  end
  
  def pie_chart
  	load_show_actions
  
   	 respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @player }
    end
  end
  
  def matches
  	load_show_actions
  	
   	 respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @player }
    end
  end
  
  
def get_player_statistics
	
		@players_games_won = 0
		@players_games_lost = 0
	  @players_games_draw = 0

		@player.teams.each do |team|
			team.matches.each do |m|
				winner_team = nil
				if(m.home_score > m.away_score)
					winner_team = m.home_team
				elsif(m.home_score < m.away_score)
					winner_team = m.away_team
				else
					@players_games_draw += 1
				end
	
				if(!winner_team.nil? && winner_team.players.include?(@player))
					@players_games_won += 1
				else
					@players_games_lost += 1
				end
			end
		end

end
  
def get_match_color(m)
		winner_team = nil

		if(m.home_score > m.away_score)
			winner_team = m.home_team
		elsif(m.home_score < m.away_score)
			winner_team = m.away_team
		else
			return 'gray'
		end

		if(winner_team.players.include?(@player))
			return 'green'
		else
			return 'red'
		end
end

  # GET /players/new
  # GET /players/new.json
  def new
    @player = Player.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @player }
    end
  end

  # GET /players/1/edit
  def edit
    @player = Player.find(params[:id])
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(params[:player])
    @player.score = 1000
    respond_to do |format|
      if @player.save
      	t = Team.create
      	t.players = [@player]
      	t.save
      	
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render json: @player, status: :created, location: @player }
      else
        format.html { render action: "new" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /players/1
  # PUT /players/1.json
  def update
    @player = Player.find(params[:id])

    respond_to do |format|
      if @player.update_attributes(params[:player])
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player = Player.find(params[:id])
    @player.destroy

    respond_to do |format|
      format.html { redirect_to players_url }
      format.json { head :ok }
    end
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<style>
	.field {padding:4px 8px 6px 8px}
</style>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%#= f.submit %>
		<input type="submit" value="Create player" name="commit" class="ui-btn ui-btn-icon-right ui-btn-corner-all ui-shadow ui-btn-up-b ui-btn-hidden" data-theme="b" aria-disabled="false">
  </div>
<% end %>

app/views/players/_historic_ranking.erb
<div data-role="content">
<script>

$(function () {

    var d = 
    [
    <% @historic_ranking_by_day.each_with_index do |log, index| %>
	[<%= log.created_at.to_i * 1000%>, <%= log.score %>]
	<% if(index != (@historic_ranking_by_day.length-1)) %>, <% end%>
    <% end %>
    ];

     $.plot($("#placeholder"), [d], { colors: ["#417daa"], xaxis: { mode: "time" },
		  grid: {
		      color: '#000',      // => primary color used for outline and labels
		      backgroundColor: '#fff', // => null for transparent, else color
		      tickColor: '#DDDDDD',  // => color used for the ticks
		      labelMargin: 3,        // => margin in pixels
		      verticalLines: true,   // => whether to show gridlines in vertical direction
		      horizontalLines: true, // => whether to show gridlines in horizontal direction
		      outlineWidth: 0        // => width of the grid outline/border in pixels
		    } ,
		    lines: { show: true },
		          points: { show: true }
    
    });
    


});
</script>

<div id="placeholder" style="width:280px;height:200px;"></div>
	<br />
	<br />
</div>

app/views/players/_historic_ranking_test.erb
<div data-role="content">
		
	
		<script>


		$(function () {
    var d = [[-373597200000, 1000], [-370918800000, 1200], [-368326800000, 1220], [-363056400000, 800], [-360378000000, 780], [-357699600000, 700]]; 

    $.plot($("#placeholder"), [d], { colors: ["#3E94F7"], xaxis: { mode: "time" },
    grid: {
        color: '#000',      // => primary color used for outline and labels
        backgroundColor: null, // => null for transparent, else color
        tickColor: '#DDDDDD',  // => color used for the ticks
        labelMargin: 3,        // => margin in pixels
        verticalLines: true,   // => whether to show gridlines in vertical direction
        horizontalLines: true, // => whether to show gridlines in horizontal direction
        outlineWidth: 1        // => width of the grid outline/border in pixels
      } ,
      lines: { show: true },
            points: { show: true }
    
    });
    
    //$("#placeholder").resize();


});

	

		</script>
	
	<div id="placeholder" style="width:100%;height:300px;"></div>
		<br />
		<br />
	</div>

app/views/players/_player_menu.erb
<div data-role="navbar">
	<ul>
		<li><a  href="<%= player_path %>" class="<%=(active_menu == 'info') ? 'ui-btn-active' : '' %>">Info</a></li>
		<li><a  href="<%= player_path %>/matches" class="<%=(active_menu == 'matches') ? 'ui-btn-active' : '' %>">Matches</a></li>
		<li><a  href="<%= player_path %>/pie-chart" class="<%=(active_menu == 'pie-chart') ? 'ui-btn-active' : '' %>">Won/Lost</a></li>
		<li><a  href="<%= player_path %>/ranking-over-time" class="<%=(active_menu == 'ranking-over-time') ? 'ui-btn-active' : '' %>">Ranking</a></li>
	</ul>
</div>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<% content_for :body do %>
<h1>Listing players</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Score</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @players.each do |player| %>
  <tr>
    <td><%= player.username %></td>
    <td><%= player.score %></td>
    <td><%= player.email %></td>
    <td><%= link_to 'Show', player %></td>
    <td><%= link_to 'Edit', edit_player_path(player) %></td>
    <td><%= link_to 'Destroy', player, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Player', new_player_path %>

<% end %>

app/views/players/matches.erb
<% content_for :body_full do %>

<div data-role="page" id="page-matches">
	  <div data-role="header" data-theme="a">
			 <a href="javascript:history.back()" data-icon="back" data-iconpos="notext" data-direction="reverse" class="ui-btn-left jqm-home">Back</a> 
			<h1><%= @player.username %> - Matches</h1>
			<a href="/" data-icon="home" data-iconpos="notext" data-direction="reverse" class="ui-btn-right jqm-home">Home</a>
		  </div>

		<%= render :partial => "/players/player_menu", :locals => { :active_menu => 'matches' } %>

	<div data-role="content">

			<div id="match-list" class="stat_view">
			<ul data-role="listview" class="ui-listview">
				<li data-role="list-divider" role="heading" class="ui-li ui-li-divider ui-btn ui-bar-d">
					Matches
				</li>
				<% @player_matches.each do |match| %>
				<li  data-theme="c" class="ui-btn ui-btn-icon-right ui-li-has-arrow ui-li ui-btn-up-c" >
					<span class="result-icon bg-<%= get_match_color(match)  %>"></span> <%= match.home_team.display_name  %> 
					(<%= match.home_score  %>) vs (<%= match.away_score  %>) <%= match.away_team.display_name  %>			 
				</li>
				<% end %>
			</ul>

			<br />
			</div>



	</div>

</div>

<% end %>

app/views/players/new.html.erb
<% content_for :body do %>

  <div data-role="header" data-theme="a">
    <h1>Add new player</h1>
    <a href="/" data-icon="home" data-iconpos="notext" data-direction="reverse" class="ui-btn-right jqm-home">Home</a>
  </div>

<%= render 'form' %>

<% end %>

app/views/players/pie_chart.erb
<% content_for :body_full do %>

<div data-role="page" id="page-pie">
		  <div data-role="header" data-theme="a">
			 <a href="javascript:history.back()" data-icon="back" data-iconpos="notext" data-direction="reverse" class="ui-btn-left jqm-home">Back</a> 
			<h1><%= @player.username %> - Pie</h1>
			<a href="/" data-icon="home" data-iconpos="notext" data-direction="reverse" class="ui-btn-right jqm-home">Home</a>
		  </div>

		<%= render :partial => "/players/player_menu", :locals => { :active_menu => 'pie-chart' } %>
	<div data-role="content">
	
	
	
	
		<script>

		$(function () {
			// data
			var data = [
				{ label: "Games lost",  data: <%= @players_games_lost %>},
				{ label: "Games won",  data: <%= @players_games_won %>},
				{ label: "Draws",  data: <%= @players_games_draw %>}
			];


			// GRAPH 1
			$.plot($("#graph"), data, 
			{
				series: {
					pie: { 
						show: true,
						background:{color:'#000'}
					}
				},
				legend: {
					show: false
				},
				colors: ["#f1375e","#7bd234", "#afb0af"]
			});
		});	
		
		
		

		</script>
		<div id="graph" class="stat_view" style="width:280px;height:280px;">

		</div>
		
		<br />
		<br />
	
	
	</div>
</div>


<% end %>

app/views/players/ranking_over_time.erb
<% content_for :body_full do %>

<div data-role="page" id="page-ranking">
		  <div data-role="header" data-theme="a">
			 <a href="javascript:history.back()" data-icon="back" data-iconpos="notext" data-direction="reverse" class="ui-btn-left jqm-home">Back</a> 
			<h1><%= @player.username %> - Ranking</h1>
			<a href="/" data-icon="home" data-iconpos="notext" data-direction="reverse" class="ui-btn-right jqm-home">Home</a>
		  </div>

		<%= render :partial => "/players/player_menu", :locals => { :active_menu => 'ranking-over-time' } %>
		<%= render 'historic_ranking' %>
</div>



<% end %>

app/views/players/show.html.erb
<% content_for :body_full do %>

<div data-role="page" id="page-info">

	  <div data-role="header" data-theme="a">
		 <a href="javascript:history.back()" data-icon="back" data-iconpos="notext" data-direction="reverse" class="ui-btn-left jqm-home">Back</a> 
		<h1><%= @player.username %></h1>
		<a href="/" data-icon="home" data-iconpos="notext" data-direction="reverse" class="ui-btn-right jqm-home">Home</a>
	  </div>

	<%= render :partial => "/players/player_menu", :locals => { :active_menu => 'info' } %>

	<div data-role="content">
		<div style="padding:0 8px 0 8px 0">

		<p id="notice"><%= notice %></p>

		<h2><%= @player.username %></h2>
		<p>
		  <b>Score:</b>
		  <%= @player.score %>
		</p>
 
		<%= render :partial => "/shared/rating", :locals => { :player => @player } %>
		<br />

		<p>
		  <b>Email:</b>
		  <%= @player.email %>
		</p>
		<br />

		</div>

	</div>
</div>

<% end %>