config/routes.rb
FIFA::Application.routes.draw do

	# staticstics
  match '/statistics/league_player_points', :controller => 'statistics', :action => 'league_player_points'
  match '/statistics/league_double_team_standings', :controller => 'statistics', :action => 'league_double_team_standings'
  match '/statistics/league_single_team_standings', :controller => 'statistics', :action => 'league_single_team_standings'

  resources :statistics

  resources :matches
  resources :teams
  
  # players
  match '/players/:id/ranking-over-time', :controller => 'players', :action => 'ranking_over_time'
  match '/players/:id/pie-chart', :controller => 'players', :action => 'pie_chart'
  match '/players/:id/matches', :controller => 'players', :action => 'matches'
  resources :players

  get "home/index"
  root :to => 'home#index'
end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :home_team, :class_name => "Team"
  belongs_to :away_team, :class_name => "Team"

  has_many :match_logs, :dependent => :delete_all

  # Dosent work, why?
  #validates :home_team_id, :uniqueness => { :scope => :away_team_id, :message => "cant be same as away team" }
  
  validates :home_score, :presence => true
  validates :away_score, :presence => true
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  before_filter :get_all_teams

  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @matches }
    end
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
    @match = Match.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @match }
    end
  end

  # GET /matches/new
  # GET /matches/new.json
  def new
    @match = Match.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @match }
    end
  end

  # GET /matches/1/edit
  def edit
    @match = Match.find(params[:id])
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(params[:match])

    all_players = @match.home_team.players + @match.away_team.players
    
    if(@match.home_team.id == @match.away_team.id)
    	raise 'Samma lag!'
    end
    
    all_players.each do |player|
    	if all_players.select{|p| p.id == player.id}.length > 1
    		raise 'Samma spelare i bada lagen'
    	end
    end 

    respond_to do |format|
      if @match.save
        MatchLog.create({:match_id => @match.id, :msg => "<strong class='log_home_team'>#{@match.home_team.display_name}</strong> just played against <strong class='log_away_team'>#{@match.away_team.display_name}</strong> and it ended #{@match.home_score} - #{@match.away_score}"})

        gm = GameManager.new
        gm.EvaluateMatch(@match)
        @match.points_trace = gm.points_trace
        @match.save
        
        write_to_player_log (all_players)
        
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render json: @match, status: :created, location: @match }
      else
        format.html { render action: "new" }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /matches/1
  # PUT /matches/1.json
  def update
    @match = Match.find(params[:id])

    respond_to do |format|
      if @match.update_attributes(params[:match])
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match = Match.find(params[:id])
    @match.destroy

    respond_to do |format|
      format.html { redirect_to matches_url }
      format.json { head :ok }
    end
  end

  protected

  def get_all_teams
    @teams = Team.all
  end

  def write_to_player_log (match_players)
    players = Player.all.to_a
    standings = players.sort_by{|p| p.score}.reverse

    match_players.each do |player|
	PlayerLog.create({:player_id => player.id, :msg => "", :score => player.score, :standing => (standings.index(player) + 1)})
    end
  end

end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_for(@match) do |f| %>
  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% @match.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<ul data-role="listview" class="ui-listview">
	<li data-role="list-divider" role="heading" class="ui-li ui-li-divider ui-btn ui-bar-d">
		<div class="ui-grid-a">
			<div class="ui-block-a" style="width:75%;">
				Home team
			</div>
			<div class="ui-block-b" style="width:20%;">
				Score
			</div>
		</div>
		
	</li>
</ul>

<div class="ui-grid-a">
	<div class="ui-block-a"  style="width:75%;">
		<select name="match[home_team_id]" id="match_home_team_id">
		    <% @teams.sort{|a,b|a.display_name <=> b.display_name}.each do |team| %>
		      <option value="<%= team.id %>">
			<%= team.display_name %>
		      </option>
		    <% end %>
		    </select>	
	</div>
	<div class="ui-block-b" style="width:20%;padding-top:10px;">
		<%= f.number_field :home_score %>	
	</div>
</div>


<ul data-role="listview" class="ui-listview">
	<li data-role="list-divider" role="heading" class="ui-li ui-li-divider ui-btn ui-bar-d">
	<div class="ui-grid-a">
			<div class="ui-block-a"  style="width:75%;">
				Away team
			</div>
			<div class="ui-block-b" style="width:20%;">
				Score
			</div>
		</div>	
	</li>
</ul>

<div class="ui-grid-a">
	<div class="ui-block-a"  style="width:75%;">
		<select name="match[away_team_id]" id="match_away_team_id">
		    <% @teams.sort{|a,b|a.display_name <=> b.display_name}.each do |team| %>
		      <option value="<%= team.id %>">
			<%= team.players.map{|p| p.username}.join(" & ") %>
		      </option>
		    <% end %>
		    </select>	
	</div>
	<div class="ui-block-b" style="width:20%;padding-top:10px;">
		    <%= f.number_field :away_score %>	
	</div>
</div>

    <div class="actions">
    <%#= f.submit %>
	<input type="submit" value="Report match" name="commit" class="ui-btn ui-btn-icon-right ui-btn-corner-all ui-shadow ui-btn-up-b ui-btn-hidden" data-theme="b" aria-disabled="false">
  </div>
<% end %>

app/views/matches/edit.html.erb
<h1>Editing match</h1>

<%= render 'form' %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<h1>Listing matches</h1>

<table>
  <tr>
    <th>Match</th>
    <th>Home score</th>
    <th>Away score</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @matches.each do |match| %>
  <tr>
    <td><strong><%= match.home_team.display_name %> VS. <%= match.away_team.display_name %></strong></td>
    <td><%= match.home_score %></td>
    <td><%= match.away_score %></td>
    <td><%= link_to 'Show', match %></td>
    <td><%= link_to 'Edit', edit_match_path(match) %></td>
    <td><%= link_to 'Destroy', match, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Match', new_match_path %>

app/views/matches/new.html.erb
<% content_for :body do %>

  <div data-role="header" data-theme="a">
    <h1>Report match</h1>
    <a href="/" data-icon="home" data-iconpos="notext" data-direction="reverse" class="ui-btn-right jqm-home">Home</a>
  </div>

<%= render 'form' %>

<% end %>

app/views/matches/show.html.erb
<% content_for :body do %>

  <div data-role="header" data-theme="a">
    <h1>Match results</h1>
    <a href="/" data-icon="home" data-iconpos="notext" data-direction="reverse" class="ui-btn-right jqm-home">Home</a>
  </div>

<div data-role="content">
<p id="notice"><%= notice %></p>

<p>
  <b>Home team:</b>
  <%= @match.home_team.display_name %>
</p>

<p>
  <b>Home score:</b>
  <%= @match.home_score %>
</p>

<p>
  <b>Away team:</b>
  <%= @match.away_team.display_name %>
</p>

<p>
  <b>Away score:</b>
  <%= @match.away_score %>
</p>

<p>
  <b>Points trace:</b><br />
  <%= raw @match.points_trace %>
</p>


<a href="/" data-role="button">To start page</a> 
</div>
<% end %>

<%#= link_to 'Edit', edit_match_path(@match) %> |
<%#= link_to 'Back', matches_path %>